[pytest]
markers =
    development: marker for dev tests
    production: marker for prod tests

#pytest -s -v -k development /tests/users/test_users.py
#pytest -s -v -k "not development"
#pytest -s -v --durations=0 -vv
